create table if not exists validated_transactions (
  transaction_id text primary key,
  source_transaction_id text,
  retry_attempt integer not null default 0,
  event_time timestamptz not null,
  emitter_account_id text not null,
  beneficiary_account_id text not null,
  emitter_pix_client_id text not null,
  beneficiary_pix_client_id text not null,
  emitter_tax_id text not null,
  beneficiary_tax_id text not null,
  amount numeric(18, 2) not null,
  currency text not null,
  status text not null,
  scenario_type text not null,
  producer_id text not null,
  trace_id text not null,
  decision_deadline timestamptz not null,
  decision_sla_seconds integer not null default 5,
  decision_status text not null default 'ACCEPTED',
  decision_reason_code text not null default 'ACCEPTED',
  decision_reason_label text not null default 'Paiement Pix accepte',
  decision_origin text not null default 'BANK',
  decision_latency_ms integer,
  decision_within_sla boolean not null default true,
  client_message text,
  validated_at timestamptz,
  enriched_at timestamptz,
  processing_node text
);

create table if not exists rejected_transactions (
  id bigserial primary key,
  transaction_id text,
  source_transaction_id text,
  retry_attempt integer not null default 0,
  event_time timestamptz,
  scenario_type text,
  producer_id text,
  trace_id text,
  rejection_type text not null,
  rejection_reason text not null,
  rejection_fingerprint text not null unique,
  decision_deadline timestamptz not null,
  decision_sla_seconds integer not null default 5,
  decision_status text not null default 'REJECTED',
  decision_reason_code text not null default 'TECHNICAL_REJECTED',
  decision_reason_label text not null default 'Paiement Pix rejete',
  decision_origin text not null default 'SYSTEM',
  decision_latency_ms integer,
  decision_within_sla boolean not null default true,
  client_message text,
  rejected_at timestamptz not null,
  processing_node text,
  original_payload jsonb not null
);
